### ISSUE TITLE
Some rocket units (e.g Katjusha) not using ammo

### ISSUE THREAD

**Issue by buumi** [spring1944/spring1944#188]
Katjusha and US support boat with rockets won't use ammo. 103.0 / 4748-e5dd41a

**Comment by buumi** [comment]
Investigated Katjusha a bit. It seems to me that RUSBM13N.lua might miss a code that decreases ammo and code which blocks shooting if there's no ammo (looked at InfantryGun.lua which has those).


    function script.BlockShot(weaponNum, targetUnitID, userTarget)

        local ammo = Spring.GetUnitRulesParam(unitID, 'ammo')
            if ammo <= 0 then
                return true
        end
        return false
    end

    function script.FireWeapon(weaponNum)
        Signal(SIG_AIM + SIG_DEPLOY)
        firing = true

        local currentAmmo = Spring.GetUnitRulesParam(unitID, 'ammo')
        Spring.SetUnitRulesParam(unitID, 'ammo', currentAmmo - 1)
    end

 That might be an wrong idea as I don't really know much about Spring development but maybe it gives then at least an idea how to fix it correctly.

**Comment by yuritch** [comment]
Thank you for the investigation. Katyusha script was indeed lacking some ammo-related parts.
Should be fixed in ba9b820f607ea1b8b88180c21d713a46f391c99f, reopen if not.

**Comment by buumi** [comment]
I think you missed Lua script change blocking and decreasing ammo for LCSS. It still can shoot forever.
