### ISSUE TITLE
Boatyards keep getting stuck

### ISSUE THREAD

**Issue by buumi** [spring1944/spring1944#192]
Boatyards keep getting stuck. At least Swedish and Hungarian ones get stuck very often but i think others do as well. They also might start producing units after a while again randomly (and then get stuck again).

**Comment by yuritch** [comment]
Will need some replays with this, or a way to reproduce it.

**Comment by buumi** [comment]
I can later try to find some replay but i think it is quite easy to reproduce. 
Pick e.g Sweden, build boatyard, built boats and accelerate game to 30x and wait for it getting stuck. It has happened probably on almost every naval game we have had so it isn't very random issue

**Comment by yuritch** [comment]
Confirmed.
Fast way: /cheat /give 1 sweboatyard /nocost
then set to repeat and order the larger boat

When it happens, a new boat is created, but always remains at 0 HP. Can be cancelled, then next ordered one will do same, etc. Even upgrading the yard doesn't work

**Comment by yuritch** [comment]
Some observations:
1. Happens when making composite ships, does not happen when making dingies
2. When it triggered, all boatyards went stuck at once. And also all land factories.
[20161125_004654_Supreme Battlefield_103.zip](https://github.com/spring1944/spring1944/files/612271/20161125_004654_Supreme.Battlefield_103.zip)

**Comment by yuritch** [comment]
Correction to previous comment: that was not it.

Way to really reproduce:
/give 1 gmtoolbox
/give 10 hunpontoontruck
deploy them all
set all yards to repeat, build one of the armed boats
set game speed to max, wait.

Interestingly it does not happen if non-composite boats are built.

**Comment by yuritch** [comment]
I think I fixed this in 4dc185ed3b2d4d6331e440879fd249d9907dd1c1,
Please test.

**Comment by yuritch** [comment]
Updated the fix in ee92408b251eec7198fa1eb11f66e3316eeb1c01 .

Looks like it is really fixed now, reopen if not.

**Comment by buumi** [comment]
Still happens on latest. Both Japan and GBR boatyard got stuck in Al-Anih game

**Comment by yuritch** [comment]
Reproduced with JPN yard.

Increased pad y coord even more, can't reproduce it now. Please test again.

**Comment by sanguinariojoe** [comment]
Hey guys!

I have been taking a look... Unfortunately I can't actually check if the patch is fixing something... Do you know a way to reproduce the problem?
I have been working with a replay. However, when the patch starts playing a role, everything is ruined due to unsynced/checksum errors... So the patch is doing "something"... 

BTW... Would you consider removing the useless building animation? It is just moving a bit the yard docks (I can do that).

**Comment by yuritch** [comment]
But why removing the animation? Does it have anything to do with the issue? The 'pad' piece never moves, and there aren't any Waits in there either, so it does not make the yard slower.

**Comment by sanguinariojoe** [comment]
I really don't think so... But I cannot be sure yet (I'm analysing the engine to know what the hell may be causing the bug).

Anyway, **In my opinion** the animation is not adding value to the game at all... So **in my opinion** is just a waste of resources

**Comment by buumi** [comment]
Sadly that's one of the irritating parts of this issue: I can't reproduce it in single player easily either, but when I play against JAL a 1vs1 for some time it happens almost every game. Sometimes it starts happening all the time and multiple yards can easily be stuck at the same time.

**Comment by yuritch** [comment]
When I tried to reproduce it (sometimes succesfully), I did that: /cheat /give 10 gbrpontoontruck, then deploy all of them, then set all of the yards to repeat build something, and set speed to 10x. Might need to give enough resources so they all keep going (or just /give 1 gmtoolbox, that unit produces enough resources on it's own).

That worked sometimes, not 100% though

**Comment by sanguinariojoe** [comment]
Well guys! I think I got it!

After building up a custom spring engine (compatible with 103.0) to check what is going on I found that effectively something is blocking the yard... However, you can move the pad as many as you want, it will still blocking the yard...
More specifically, in the replay I'm using right now (Buumi sent it to me), the blocking object is...












...













**ger_sboot_turret_20mm_front**
A child turret!

I'm pretty positive that the problem is the engine is not updating the blocking data because the turret is not never moving (the partner is moving, not the turret itself), and therefore the yard get stuck until the turret is not destroyed.

Nevertheless, the simplest solution is adding `blocking = false` to all the boat child unit definitions (hopefully it is fixing the bug, but I cannot test, :-/)

**Comment by buumi** [comment]
That would be great! Let's hope the best. :) 

As we don't know how to reliably reproduce it you can probably just commit probable fix into master and we play a few naval games with JAL. In the past this has always revealed whether the fix has worked. You can also try what yuri suggested but I had issues getting it to reproduce reliably in SP.

**Comment by yuritch** [comment]
I just committed 0141030 to set all boatchild units to blocking = false

**Comment by buumi** [comment]
Over 5 naval games without issues now, some of which were long and with multiple factions. I guess this can be closed with pretty good certainty that it's fixed for real. If it really appears again then let's just reopen.. Thanks a  lot for @sanguinariojoe and @yuritch!
