### ISSUE TITLE
rifles firing uphill don't impact targets occasionally

### ISSUE THREAD

**Issue by kanatohodets** [spring1944/spring1944#37]
perhaps something to do with the intensity fade out

**Comment by ashdnazg** [comment]
This needs to be reproduced in development version. (I couldn't)

**Comment by ashdnazg** [comment]
Please verify that this was fixed

**Comment by kanatohodets** [comment]
https://springrts.com/mantis/view.php?id=4661 references something similar. sounds like 99.0 will resolve this, burnblow or not. It does still happen in latest S44 git (I saw it in a few recent games -- inf up on a hill not getting hit; shots passing through them).

**Comment by ashdnazg** [comment]
Of course it happens on S44 git, because I think I only added it on sweden...

**Comment by kanatohodets** [comment]
ha, indeed! my bad, didn't notice that your change was on sweden.

**Comment by ashdnazg** [comment]
Should be fixed here: https://github.com/spring1944/spring1944/commit/7f85ea9d5f9f8af23e335784b462273acb1fbea9
